import {
  Body,
  Controller,
  Get,
  Post,
  Query,
  UseGuards,
} from "@nestjs/common";
import {
  CurrentUser,
  JwtPayload,
} from "../../common/decorators/current-user.decorator";
import {
  ApiBearerAuth,
  ApiOperation,
  ApiQuery,
  ApiResponse,
  ApiTags,
} from "@nestjs/swagger";
import { Throttle } from "@nestjs/throttler";
import { v4 as uuidv4 } from "uuid";
import { JwtAuthGuard } from "../../common/guards/jwt-auth.guard";
import { S3Service } from "../../common/s3/s3.service";
import { UploadUrlDto } from "./dto/upload-url.dto";

@ApiTags("Files")
@ApiBearerAuth()
@UseGuards(JwtAuthGuard)
@Controller("files")
export class FilesController {
  constructor(private readonly s3: S3Service) {}

  @Post("upload-url")
  @Throttle({ short: { limit: 20, ttl: 60_000 } })
  @ApiOperation({
    summary: "Generar presigned URL para subir un PDF a S3",
    description:
      "Retorna una URL PUT pre-firmada válida por 10 minutos. Solo se aceptan PDFs.",
  })
  @ApiResponse({
    status: 201,
    schema: {
      example: {
        uploadUrl: "https://sistema-notaria.s3.amazonaws.com/...",
        key: "pdfs/2026/05/uuid.pdf",
        expiresIn: 600,
      },
    },
  })
  async getUploadUrl(@Body() dto: UploadUrlDto) {
    // Key is always generated by the backend — never from user input
    // Extension is forced to .pdf regardless of filename
    const year = new Date().getFullYear();
    const month = String(new Date().getMonth() + 1).padStart(2, "0");
    const key = `pdfs/${year}/${month}/${uuidv4()}.pdf`;

    const uploadUrl = await this.s3.getPresignedUploadUrl(
      key,
      "application/pdf", // Forced — not from user input
      600,
    );
    return { uploadUrl, key, expiresIn: 600 };
  }

  @Get("view-url")
  // presigned view URLs: una galería puede pedir varias de golpe.
  @Throttle({ short: { limit: 100, ttl: 60_000 } })
  @ApiOperation({
    summary: "Generar presigned URL para ver/descargar un archivo de S3",
    description: "Retorna una URL GET pre-firmada válida por 1 hora.",
  })
  @ApiQuery({
    name: "key",
    required: true,
    example: "pdfs/2026/05/uuid.pdf",
    description: "Key del archivo en S3 (debe comenzar con pdfs/)",
  })
  @ApiResponse({
    status: 200,
    schema: {
      example: {
        viewUrl: "https://sistema-notaria.s3.amazonaws.com/...",
        expiresIn: 3600,
      },
    },
  })
  async getViewUrl(
    @Query("key") key: string,
    @CurrentUser() user: JwtPayload,
  ) {
    // Validate key format to prevent path traversal or unauthorized access
    if (!key || !/^(pdfs|uploads)\/[\w\-/]+\.(pdf|jpg|jpeg|png|webp)$/i.test(key)) {
      return { error: "Key de archivo inválida" };
    }
    // Restricted users get an inline, short-lived, non-cacheable URL so the
    // browser previews it in an <iframe> without the front pulling the whole
    // blob into memory, and the bytes are not retained on disk.
    const restricted = !!user.pdfDownloadDisabled;
    const disposition = restricted ? "inline" : "attachment";
    const expiresIn = restricted ? 60 : 3600;
    const cacheControl = restricted ? "no-store" : undefined;
    const viewUrl = await this.s3.getSignedUrl(
      key,
      expiresIn,
      disposition,
      cacheControl,
    );
    return { viewUrl, expiresIn, downloadRestricted: restricted };
  }
}
